/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "https://zwoj43jrqjal3obn2badkxrmoe.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-7cqti5hhvndpxdebktj6xkhudy",
    "aws_cognito_identity_pool_id": "eu-west-1:9a2843bf-e959-4839-8db6-46d5985cfe55",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_we3M5a5Ur",
    "aws_user_pools_web_client_id": "6rig9r1hfotjp5dj3lan3sh05j",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
